version: 2
jobs:
  build:
    docker:
      - image: node:8
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install yarn
          command: |
            yarn --version
#     - restore_cache:
#         keys:
#         - v1-dependencies-{{ checksum "yarn.lock" }}
#         - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: yarn add lerna -D
      - run: yarn run bootstrap
      - run: yarn test

